/* ============================================================================
   kaymen.dev — main site interactions

   Ported from mockup/v3-quiet.html (2026-08-15): rail scroll-spy + sliding
   lozenge, scroll-progress hairline, reveal-on-scroll, the fleet panel and the
   routing question. Plus the idea form, which is ours and not in the mockup.

   Every block guards its own elements: the rail ships on /work and every case
   study too, where the homepage-only sections simply are not in the DOM.

   The theme toggle was removed with the redesign. The new palette is
   light-first and no dark variant is designed yet — see
   HANDOFF-REDESIGN-2026-08-15.md §5. Do not re-add a half-working one.
   ============================================================================ */

(function () {
  'use strict';

  var links = Array.prototype.slice.call(document.querySelectorAll('.rail-link'));
  var tabs = Array.prototype.slice.call(document.querySelectorAll('.tab'));
  var loz = document.getElementById('lozenge');
  var prog = document.getElementById('prog');
  var secs = links.map(function (l) { return document.getElementById(l.dataset.sec); });

  /* ---- the lozenge follows the active item ------------------------------ */
  function moveLozenge(i) {
    var el = links[i];
    if (!el || !loz) return;
    loz.style.transform = 'translateY(' + el.offsetTop + 'px)';
  }
  function setActive(id) {
    links.forEach(function (l, i) {
      var on = l.dataset.sec === id;
      l.classList.toggle('on', on);
      if (on) moveLozenge(i);
    });
    tabs.forEach(function (t) { t.classList.toggle('on', t.dataset.sec === id); });
  }

  /* ---- scroll spy -------------------------------------------------------- */
  if (window.IntersectionObserver) {
    var spy = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) setActive(e.target.id);
      });
    }, { rootMargin: '-45% 0px -50% 0px', threshold: 0 });
    secs.forEach(function (s) { if (s) spy.observe(s); });
  }

  /* ---- scroll progress on the rail hairline ------------------------------ */
  if (prog) {
    var ticking = false;
    var onScroll = function () {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(function () {
        var max = document.documentElement.scrollHeight - window.innerHeight;
        var p = max > 0 ? Math.min(1, window.scrollY / max) : 0;
        prog.style.height = (p * 100) + '%';
        ticking = false;
      });
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
  }

  /* ---- reveal on scroll --------------------------------------------------
     Without IntersectionObserver .rv would stay at opacity 0 forever, so the
     fallback reveals everything rather than hiding the page. */
  var revealables = document.querySelectorAll('.rv');
  if (window.IntersectionObserver) {
    var rev = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) { e.target.classList.add('in'); rev.unobserve(e.target); }
      });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.06 });
    Array.prototype.forEach.call(revealables, function (el) { rev.observe(el); });
  } else {
    Array.prototype.forEach.call(revealables, function (el) { el.classList.add('in'); });
  }

  /* ---- the fleet panel ---------------------------------------------------
     Nothing to do here any more. The panel is server-rendered from
     content/stats.js (generated by scripts/refresh-stats.js from each
     project's git history), so the bars are in the HTML a crawler sees and
     there is no client-side array anyone can quietly edit. It used to be a
     hand-typed placeholder series, which is the one thing
     HANDOFF-REDESIGN-2026-08-15.md §5 said must not ship. */

  /* ---- the picker ---------------------------------------------------------
     ONE section answers both "what do you need" and "what does it cost". The
     page used to ask those separately, in #need and #price, which was the same
     question twice for 2,046px of homepage.

     index.html renders an empty shell. Every string below comes from
     window.KD_PRICING (content/pricing.js) — the same file server/render.js
     require()s for the case-study cost blocks. One ladder, two readers, and no
     second copy in this file to keep in step by hand. There used to be one.

     The sentence and the pills are two ways into ONE state. Neither owns it, so
     they cannot drift apart: whichever the visitor reaches for, `askSel` moves
     and both re-render. The redundancy is deliberate — if somebody never notices
     the underlined phrase is a control, the pills still work. */
  var askChips = document.getElementById('askChips');
  if (askChips && window.KD_PRICING) {
    var ASK = window.KD_PRICING.routes();
    var askSay = document.getElementById('askSay');
    var askPop = document.getElementById('askPop');
    var askVeil = document.getElementById('askVeil');
    var askSel = 'stack';
    var askEsc = function (s) {
      return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
    };

    /* Built once, then only classes and text change. Re-rendering the row on
       every pick would throw focus off the control just used, which is merely
       untidy with a mouse and unusable with a keyboard. */
    askChips.innerHTML = ASK.map(function (r) {
      return '<button class="ask-chip' + (r.id === 'unsure' ? ' alt' : '') + '"' +
        ' data-id="' + r.id + '" role="option" aria-selected="false">' +
        '<b>' + askEsc(r.chip) + '</b><span>' + askEsc(r.price) + '</span></button>';
    }).join('');
    askChips.querySelectorAll('.ask-chip').forEach(function (c) {
      c.addEventListener('click', function () { askSel = c.dataset.id; askRender(); });
    });

    var askPopClose = function () {
      askPop.hidden = true;
      askVeil.hidden = true;
      askSay.setAttribute('aria-expanded', 'false');
    };

    var askPopOpen = function () {
      askPop.innerHTML = '<div class="hd">Pick the closest</div>' + ASK.map(function (r) {
        return '<button data-id="' + r.id + '" role="option" aria-selected="' +
          (r.id === askSel) + '"' + (r.id === askSel ? ' class="on"' : '') + '>' +
          '<span>' + askEsc(r.name) + '</span>' +
          '<i>' + askEsc(r.note) + '  ·  ' + askEsc(r.price) + '</i></button>';
      }).join('');
      askPop.querySelectorAll('button').forEach(function (b) {
        b.addEventListener('click', function () {
          askSel = b.dataset.id; askPopClose(); askRender();
        });
      });
      askPop.hidden = false;
      askVeil.hidden = false;
      askSay.setAttribute('aria-expanded', 'true');

      /* Anchored under the phrase, flipped above it when it would run off the
         bottom, clamped to the viewport on both sides. It is position:fixed, so
         it does not follow the page — hence the scroll listener below. */
      var box = askSay.getBoundingClientRect();
      var top = box.bottom + 8;
      var left = Math.min(Math.max(12, box.left), window.innerWidth - askPop.offsetWidth - 12);
      if (top + askPop.offsetHeight > window.innerHeight - 12) {
        top = Math.max(12, box.top - askPop.offsetHeight - 8);
      }
      askPop.style.top = top + 'px';
      askPop.style.left = left + 'px';
    };

    askSay.addEventListener('click', function () {
      if (askPop.hidden) askPopOpen(); else askPopClose();
    });
    askVeil.addEventListener('click', askPopClose);
    window.addEventListener('scroll', function () {
      if (!askPop.hidden) askPopClose();
    }, { passive: true });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && !askPop.hidden) askPopClose();
    });

    var askRender = function () {
      var r = ASK.filter(function (x) { return x.id === askSel; })[0];
      if (!r) return;
      askSay.textContent = r.say;
      document.getElementById('askNote').textContent = r.note;
      document.getElementById('askTicks').innerHTML = r.ticks.map(function (t) {
        return '<li>' + askEsc(t) + '</li>';
      }).join('');
      document.getElementById('askBuild').innerHTML =
        askEsc(r.n1) + '<span>' + askEsc(r.s1) + '</span>';
      document.getElementById('askMonthly').innerHTML =
        askEsc(r.n2) + '<span>' + askEsc(r.s2) + '</span>';
      askChips.querySelectorAll('.ask-chip').forEach(function (c) {
        var on = c.dataset.id === askSel;
        c.classList.toggle('on', on);
        c.setAttribute('aria-selected', on);
      });
    };
    askRender();
  }

  /* ---- idea form ----------------------------------------------------------
     Not in the mockup — the mockup's contact buttons were placeholders. This
     posts to /api/contact, which is rate-limited and gated on the honeypot
     (_hp) plus time-to-submit (_t). */
  var ideaForm = document.getElementById('ideaForm');
  var loadedAt = Date.now();
  if (ideaForm) {
    ideaForm.addEventListener('submit', async function (e) {
      e.preventDefault();
      var btn = document.getElementById('ideaSubmitBtn');
      var msg = document.getElementById('ideaMsg');
      btn.textContent = 'Sending…';
      btn.disabled = true;
      msg.innerHTML = '';
      try {
        var res = await fetch('/api/contact', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            name: document.getElementById('ideaName').value,
            email: document.getElementById('ideaEmail').value,
            project_name: document.getElementById('ideaProject').value,
            message: document.getElementById('ideaText').value,
            _hp: document.getElementById('ideaWebsite').value,
            _t: Date.now() - loadedAt
          })
        });
        var data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed to send');
        msg.innerHTML = '<div class="success-msg">Sent. We\'ll come back to you within 24 hours.</div>';
        ideaForm.reset();
      } catch (err) {
        msg.innerHTML = '<div class="error-msg">' + String(err.message).replace(/</g, '&lt;') + '</div>';
      }
      btn.textContent = 'Send it over';
      btn.disabled = false;
    });
  }

  /* ---- lozenge needs a first position once fonts settle ------------------- */
  function parkLozenge() {
    var i = links.findIndex(function (l) { return l.classList.contains('on'); });
    moveLozenge(i < 0 ? 0 : i);
  }
  window.addEventListener('load', parkLozenge);
  parkLozenge();

  /* ---- the rail sits exactly midway between the screen edge and the text ---
     styles.css derives --text-left from 100vw, which is close but includes the
     scrollbar — about 4px out on Windows, and "exactly between" was the ask. So
     measure the real text edge and hand it back. documentElement.clientWidth,
     not innerWidth: the former excludes the scrollbar, which is the whole point.
     If there is no .wrap on the page the CSS fallback stands. */
  var railFrame = 0;
  function syncRailGutter() {
    railFrame = 0;
    var root = document.documentElement;

    var wrap = document.querySelector('.page .wrap') || document.querySelector('.wrap');
    if (wrap) {
      var rect = wrap.getBoundingClientRect();
      if (rect.width) {
        var pad = parseFloat(getComputedStyle(wrap).paddingLeft) || 0;
        var edge = document.body.classList.contains('rail-right')
          ? root.clientWidth - rect.right + pad
          : rect.left + pad;
        root.style.setProperty('--text-left', Math.round(edge) + 'px');
      }
    }

    /* Vertical: level the rail with the top of the page title. Measured rather
       than hard-coded so it survives a change to the hero padding, and measured
       in DOCUMENT coordinates because the rail is fixed and the reader lands at
       the top of the page. Every page has a first h1: the hero on the homepage,
       the case title on a case study. */
    var title = document.querySelector('.page h1') || document.querySelector('h1');
    if (title) {
      /* offsetTop, not getBoundingClientRect: the hero carries the .rv reveal,
         which starts life translated down the page. A rect measured before the
         reveal fires is the animated position, not the layout one, and the rail
         ends up 14px low forever. The offset chain ignores transforms. */
      var top = 0;
      for (var el = title; el; el = el.offsetParent) top += el.offsetTop;
      if (top > 0) root.style.setProperty('--rail-top', Math.round(top) + 'px');
    }
  }
  function queueRailGutter() {
    if (!railFrame) railFrame = requestAnimationFrame(syncRailGutter);
  }
  window.addEventListener('resize', queueRailGutter);
  window.addEventListener('load', syncRailGutter);
  syncRailGutter();
})();
