/* ============================================================================
   kaymen.dev — main site interactions

   Ported from mockup/v3-quiet.html (2026-08-15): rail scroll-spy + sliding
   lozenge, scroll-progress hairline, reveal-on-scroll, the fleet panel and the
   routing question. Plus the idea form, which is ours and not in the mockup.

   Every block guards its own elements: the rail ships on /work and every case
   study too, where the homepage-only sections simply are not in the DOM.

   The theme toggle was removed with the redesign. The new palette is
   light-first and no dark variant is designed yet — see
   HANDOFF-REDESIGN-2026-08-15.md §5. Do not re-add a half-working one.
   ============================================================================ */

(function () {
  'use strict';

  var links = Array.prototype.slice.call(document.querySelectorAll('.rail-link'));
  var tabs = Array.prototype.slice.call(document.querySelectorAll('.tab'));
  var loz = document.getElementById('lozenge');
  var prog = document.getElementById('prog');
  var secs = links.map(function (l) { return document.getElementById(l.dataset.sec); });

  /* ---- the lozenge follows the active item ------------------------------ */
  function moveLozenge(i) {
    var el = links[i];
    if (!el || !loz) return;
    loz.style.transform = 'translateY(' + el.offsetTop + 'px)';
  }
  function setActive(id) {
    links.forEach(function (l, i) {
      var on = l.dataset.sec === id;
      l.classList.toggle('on', on);
      if (on) moveLozenge(i);
    });
    tabs.forEach(function (t) { t.classList.toggle('on', t.dataset.sec === id); });
  }

  /* ---- scroll spy -------------------------------------------------------- */
  if (window.IntersectionObserver) {
    var spy = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) setActive(e.target.id);
      });
    }, { rootMargin: '-45% 0px -50% 0px', threshold: 0 });
    secs.forEach(function (s) { if (s) spy.observe(s); });
  }

  /* ---- scroll progress on the rail hairline ------------------------------ */
  if (prog) {
    var ticking = false;
    var onScroll = function () {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(function () {
        var max = document.documentElement.scrollHeight - window.innerHeight;
        var p = max > 0 ? Math.min(1, window.scrollY / max) : 0;
        prog.style.height = (p * 100) + '%';
        ticking = false;
      });
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
  }

  /* ---- reveal on scroll --------------------------------------------------
     Without IntersectionObserver .rv would stay at opacity 0 forever, so the
     fallback reveals everything rather than hiding the page. */
  var revealables = document.querySelectorAll('.rv');
  if (window.IntersectionObserver) {
    var rev = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (e.isIntersecting) { e.target.classList.add('in'); rev.unobserve(e.target); }
      });
    }, { rootMargin: '0px 0px -8% 0px', threshold: 0.06 });
    Array.prototype.forEach.call(revealables, function (el) { rev.observe(el); });
  } else {
    Array.prototype.forEach.call(revealables, function (el) { el.classList.add('in'); });
  }

  /* ---- the fleet panel ---------------------------------------------------
     Nothing to do here any more. The panel is server-rendered from
     content/stats.js (generated by scripts/refresh-stats.js from each
     project's git history), so the bars are in the HTML a crawler sees and
     there is no client-side array anyone can quietly edit. It used to be a
     hand-typed placeholder series, which is the one thing
     HANDOFF-REDESIGN-2026-08-15.md §5 said must not ship. */

  /* ---- routing question --------------------------------------------------- */
  var ANSWERS = {
    build: {
      t: 'A build, then a plan that keeps it alive',
      b: 'We scope it, build it, and hand it over running, on your infrastructure and in your accounts. Then it moves onto a maintenance plan, priced into the contract from day one. No cliff at launch.',
      l: ['Three to four complete design directions, never one', 'Working builds as we go, not a reveal at the end', 'Ends with a handover document, not a support ticket'],
      p: 'from $2,500', per: 'to build · then from $200/mo'
    },
    run: {
      t: 'Adoption of something we did not build',
      b: 'First a read of what exists. What it runs on, what is going to break, what is undocumented. Then it goes on a plan. Most inherited systems need somewhere between one and eight active days a month.',
      l: ['Backups verified, not assumed to exist', 'Security patches and dependency updates', 'Someone who answers when it breaks'],
      p: 'from $450/mo', per: 'we take it as it is · no build fee'
    },
    unsure: {
      t: 'A straight answer about whether this is software at all',
      b: 'Sometimes it is a process problem wearing a software costume, and the honest answer is not to build anything. That conversation is free and we will tell you if the answer is no.',
      l: ['No payment, no commitment to a package', 'We will name the cheaper option if there is one', 'If it is worth building, you leave with a shape and a number'],
      p: 'Free', per: 'one conversation'
    }
  };
  var answer = document.getElementById('answer');
  if (answer) {
    document.querySelectorAll('.q').forEach(function (q) {
      q.addEventListener('click', function () {
        var key = q.dataset.answer;
        var open = q.getAttribute('aria-pressed') === 'true';
        document.querySelectorAll('.q').forEach(function (o) { o.setAttribute('aria-pressed', 'false'); });
        if (open) { answer.classList.remove('on'); return; }
        q.setAttribute('aria-pressed', 'true');
        var a = ANSWERS[key];
        if (!a) return;
        document.getElementById('aTitle').textContent = a.t;
        document.getElementById('aBody').textContent = a.b;
        document.getElementById('aList').innerHTML = a.l.map(function (x) {
          return '<li>' + x.replace(/&/g, '&amp;').replace(/</g, '&lt;') + '</li>';
        }).join('');
        document.getElementById('aPrice').textContent = a.p;
        document.getElementById('aPer').textContent = a.per;
        answer.classList.add('on');
      });
    });
  }

  /* ---- the estimate builder -----------------------------------------------
     THE LADDER LIVES HERE. index.html renders an empty shell; every price on the
     pricing section comes from these two arrays, so there is one place to change
     them and no chance of the markup and the copy drifting apart.

     Derived from measured build effort (content/stats.js, generated from git
     history) at $125/hr. See unified-memory/projects/kaymen-group/
     retainer-pricing-ladder.md for where the monthlies came from.

     Only "from" prices are published. A ceiling makes a client with a smaller
     budget assume you are coming for the ceiling, so the total is a consequence
     of what they tick and nothing else. */
  var EST_BASES = [
    { id: 'running', from: 0, mo: 450,
      name: 'It already exists. It just needs someone to run it.',
      note: 'Code we did not write takes more looking after, which is why this is not the cheapest line here.',
      plan: 'Patched, backed up, monitored, and small changes as they come up.' },
    { id: 'tool', from: 2500, mo: 200,
      name: 'One job you still do by hand',
      note: 'A form, a tracker, the report somebody rebuilds every week. One thing, done properly.',
      plan: 'Patched, backed up, monitored, and we answer.' },
    { id: 'stack', from: 6500, mo: 450,
      name: 'Work spread across tools that do not talk to each other',
      note: 'You have the software. What you do not have is one place where the answer lives, so somebody reconciles it by hand.',
      plan: 'Kept running, plus the small changes as they come up.' },
    { id: 'platform', from: 15000, mo: 1200,
      name: 'Several systems, several teams, and the reporting across all of it',
      note: 'Questions that can only be answered today by exporting everything and merging it.',
      plan: '10 hours of development a month, rolling over one month.' }
  ];

  var EST_ADDONS = [
    { id: 'mobile', add: 5000, mo: 300, name: 'An app in the App Store and Google Play',
      note: 'Native, in both stores, updated over the air. Apple and Google force SDK bumps, so an unmaintained app dies in about 18 months.' },
    { id: 'connect', add: 2500, mo: 0, name: 'Connect to something you already run',
      note: 'A CRM, an accounting system, a bank feed. Per system connected.' },
    { id: 'portal', add: 2500, mo: 0, name: 'Logins for your own customers',
      note: 'They see their own data and nothing else. Their questions stop arriving by email.' },
    { id: 'tenant', add: 3500, mo: 300, name: 'More than one location, brand or tenant',
      note: 'Separate data, one platform, and reporting that crosses all of them.' },
    { id: 'migrate', add: 1500, mo: 0, name: 'Bring your existing data across',
      note: 'The spreadsheets, the old system, the history. Reconciled, not just imported.' },
    { id: 'lang', add: 1500, mo: 0, name: 'A second language',
      note: 'Including right-to-left, which is a layout problem rather than a translation one.' },
    { id: 'sso', add: 2500, mo: 500, name: 'SSO, audit trail, compliance',
      note: 'Single sign-on, an immutable log of who did what, and the paperwork that goes with it.' }
  ];

  var EST_PARTNER_AT = 15000;   // above this a fixed build price stops being honest

  var estBases = document.getElementById('estBases');
  if (estBases) {
    var estBase = 'stack';
    var estPicked = {};
    var estMoney = function (n) { return '$' + Math.round(n).toLocaleString('en-US'); };

    var estRow = function (o, kind) {
      var on = kind === 'base' ? estBase === o.id : !!estPicked[o.id];
      var price = kind === 'base'
        ? (o.from ? 'from ' + estMoney(o.from) : 'no build')
        : '+' + estMoney(o.add);
      return '<label class="opt' + (on ? ' on' : '') + '">' +
        '<input type="' + (kind === 'base' ? 'radio" name="estbase' : 'checkbox') +
        '" value="' + o.id + '"' + (on ? ' checked' : '') + '>' +
        '<span class="t"><b>' + o.name + '</b><span>' + o.note + '</span></span>' +
        '<span class="p">' + price + '</span></label>';
    };

    /* Built ONCE, then only the classes and the total change. Re-rendering the
       list on every tick would throw focus off the control the user just used,
       which is fine with a mouse and unusable with a keyboard. */
    estBases.innerHTML = EST_BASES.map(function (b) { return estRow(b, 'base'); }).join('');
    document.getElementById('estAddons').innerHTML =
      EST_ADDONS.map(function (a) { return estRow(a, 'add'); }).join('');

    estBases.querySelectorAll('input').forEach(function (i) {
      i.addEventListener('change', function () { estBase = i.value; estRender(); });
    });
    document.getElementById('estAddons').querySelectorAll('input').forEach(function (i) {
      i.addEventListener('change', function () { estPicked[i.value] = i.checked; estRender(); });
    });

    var estRender = function () {
      estBases.querySelectorAll('.opt').forEach(function (el) {
        el.classList.toggle('on', el.querySelector('input').checked);
      });
      document.getElementById('estAddons').querySelectorAll('.opt').forEach(function (el) {
        el.classList.toggle('on', el.querySelector('input').checked);
      });

      var b = EST_BASES.filter(function (x) { return x.id === estBase; })[0];
      var chosen = EST_ADDONS.filter(function (a) { return estPicked[a.id]; });
      var build = b.from + chosen.reduce(function (s, a) { return s + a.add; }, 0);
      var monthly = b.mo + chosen.reduce(function (s, a) { return s + a.mo; }, 0);

      /* nothing to build means nothing to add on to, so the whole second step
         goes away rather than sitting there offering to price a rebuild */
      document.getElementById('estAddonStep').hidden = !b.from;
      if (!b.from) {
        estPicked = {}; chosen = []; build = 0; monthly = b.mo;
        document.getElementById('estAddons').querySelectorAll('input').forEach(function (i) {
          i.checked = false; i.closest('.opt').classList.remove('on');
        });
      }

      document.getElementById('estLbl').textContent = b.from ? 'Starting around' : 'Nothing to build';
      document.getElementById('estTotal').innerHTML = b.from
        ? estMoney(build) + '<small> to build</small>'
        : '<small style="font-size:15px">We take it as it is</small>';
      document.getElementById('estMonthly').innerHTML = estMoney(monthly) + '<span>/month</span>';
      document.getElementById('estPlan').textContent = b.plan;

      document.getElementById('estPicked').innerHTML = (b.from
        ? '<div><span>' + b.name + '</span><b>' + estMoney(b.from) + '</b></div>' : '') +
        chosen.map(function (a) {
          return '<div><span>' + a.name + '</span><b>+' + estMoney(a.add) + '</b></div>';
        }).join('');

      var flip = document.getElementById('estFlip');
      if (build >= EST_PARTNER_AT) {
        flip.hidden = false;
        flip.innerHTML = '<b>At this size most people take the partnership instead</b>' +
          '<p><em>No build fee at all.</em> You commit to twelve months at $3,500/mo and we start next week. ' +
          'It works out lower than the number above in year one, and you are not writing a large cheque before anything exists.</p>';
      } else {
        flip.hidden = true;
      }
    };
    estRender();
  }

  /* ---- idea form ----------------------------------------------------------
     Not in the mockup — the mockup's contact buttons were placeholders. This
     posts to /api/contact, which is rate-limited and gated on the honeypot
     (_hp) plus time-to-submit (_t). */
  var ideaForm = document.getElementById('ideaForm');
  var loadedAt = Date.now();
  if (ideaForm) {
    ideaForm.addEventListener('submit', async function (e) {
      e.preventDefault();
      var btn = document.getElementById('ideaSubmitBtn');
      var msg = document.getElementById('ideaMsg');
      btn.textContent = 'Sending…';
      btn.disabled = true;
      msg.innerHTML = '';
      try {
        var res = await fetch('/api/contact', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            name: document.getElementById('ideaName').value,
            email: document.getElementById('ideaEmail').value,
            project_name: document.getElementById('ideaProject').value,
            message: document.getElementById('ideaText').value,
            _hp: document.getElementById('ideaWebsite').value,
            _t: Date.now() - loadedAt
          })
        });
        var data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed to send');
        msg.innerHTML = '<div class="success-msg">Sent. We\'ll come back to you within 24 hours.</div>';
        ideaForm.reset();
      } catch (err) {
        msg.innerHTML = '<div class="error-msg">' + String(err.message).replace(/</g, '&lt;') + '</div>';
      }
      btn.textContent = 'Send it over';
      btn.disabled = false;
    });
  }

  /* ---- lozenge needs a first position once fonts settle ------------------- */
  function parkLozenge() {
    var i = links.findIndex(function (l) { return l.classList.contains('on'); });
    moveLozenge(i < 0 ? 0 : i);
  }
  window.addEventListener('load', parkLozenge);
  parkLozenge();

  /* ---- the rail sits exactly midway between the screen edge and the text ---
     styles.css derives --text-left from 100vw, which is close but includes the
     scrollbar — about 4px out on Windows, and "exactly between" was the ask. So
     measure the real text edge and hand it back. documentElement.clientWidth,
     not innerWidth: the former excludes the scrollbar, which is the whole point.
     If there is no .wrap on the page the CSS fallback stands. */
  var railFrame = 0;
  function syncRailGutter() {
    railFrame = 0;
    var root = document.documentElement;

    var wrap = document.querySelector('.page .wrap') || document.querySelector('.wrap');
    if (wrap) {
      var rect = wrap.getBoundingClientRect();
      if (rect.width) {
        var pad = parseFloat(getComputedStyle(wrap).paddingLeft) || 0;
        var edge = document.body.classList.contains('rail-right')
          ? root.clientWidth - rect.right + pad
          : rect.left + pad;
        root.style.setProperty('--text-left', Math.round(edge) + 'px');
      }
    }

    /* Vertical: level the rail with the top of the page title. Measured rather
       than hard-coded so it survives a change to the hero padding, and measured
       in DOCUMENT coordinates because the rail is fixed and the reader lands at
       the top of the page. Every page has a first h1: the hero on the homepage,
       the case title on a case study. */
    var title = document.querySelector('.page h1') || document.querySelector('h1');
    if (title) {
      /* offsetTop, not getBoundingClientRect: the hero carries the .rv reveal,
         which starts life translated down the page. A rect measured before the
         reveal fires is the animated position, not the layout one, and the rail
         ends up 14px low forever. The offset chain ignores transforms. */
      var top = 0;
      for (var el = title; el; el = el.offsetParent) top += el.offsetTop;
      if (top > 0) root.style.setProperty('--rail-top', Math.round(top) + 'px');
    }
  }
  function queueRailGutter() {
    if (!railFrame) railFrame = requestAnimationFrame(syncRailGutter);
  }
  window.addEventListener('resize', queueRailGutter);
  window.addEventListener('load', syncRailGutter);
  syncRailGutter();
})();
