/* ============================================================================
   kaymen.dev — the price ladder

   SINGLE SOURCE OF TRUTH. Everything that quotes a price reads this file:

     · the estimate builder on /#price      (script.js, via window.KD_PRICING)
     · the cost block on every case study   (server/render.js)
     · the routing-question answers         (script.js)

   It used to live inside script.js, which meant the case studies could not see
   it and would have had to repeat the numbers. Repeated numbers drift, and a
   pricing page that disagrees with a case study is worse than either alone.

   WHERE THE NUMBERS CAME FROM
   Build tiers and add-on increments are derived from measured build effort in
   content/stats.js — generated by scripts/refresh-stats.js from real git
   history — priced at the $125/hr overflow rate. The monthlies come from the
   measured maintenance load recorded in
   unified-memory/projects/kaymen-group/retainer-pricing-ladder.md: a live
   system needs 1–8 active days a month, clustering at 2–5, and a maintenance
   day is 2–3 focused hours rather than eight.

   ONLY "FROM" PRICES ARE PUBLISHED. A published ceiling makes a client with a
   smaller budget assume you are coming for the ceiling. The total is a
   consequence of what they tick and nothing else.
   ============================================================================ */

const OVERFLOW_HOURLY = 125;

/* The pilot. A cheaper BUILD would devalue the work and attract clients who
   churn off the retainer, which is where the business actually is. A cheap paid
   pilot lowers the first step without either problem, and buys the scope
   clarity you need before quoting. */
const PILOT = { price: 750, weeks: 1 };

/* Above this a fixed build price stops being one we can deliver at, so the
   builder stops quoting and offers the partnership instead. */
const PARTNER_AT = 15000;
const PARTNER = { monthly: 3500, months: 12 };

const BASES = [
  {
    id: 'running', from: 0, mo: 450,
    name: 'It already exists. It just needs someone to run it.',
    note: 'Code we did not write takes more looking after, which is why this is not the cheapest line here.',
    plan: 'Patched, backed up, monitored, and small changes as they come up.',
  },
  {
    id: 'tool', from: 2500, mo: 200,
    name: 'One job you still do by hand',
    note: 'A form, a tracker, the report somebody rebuilds every week. One thing, done properly.',
    plan: 'Patched, backed up, monitored, and we answer.',
  },
  {
    id: 'stack', from: 6500, mo: 450,
    name: 'Work spread across tools that do not talk to each other',
    note: 'You have the software. What you do not have is one place where the answer lives, so somebody reconciles it by hand.',
    plan: 'Kept running, plus the small changes as they come up.',
  },
  {
    id: 'platform', from: 15000, mo: 1200,
    name: 'Several systems, several teams, and the reporting across all of it',
    note: 'Questions that can only be answered today by exporting everything and merging it.',
    plan: '10 hours of development a month, rolling over one month.',
  },
];

const ADDONS = [
  { id: 'mobile', add: 5000, mo: 300, name: 'An app in the App Store and Google Play',
    note: 'Native, in both stores, updated over the air. Apple and Google force SDK bumps, so an unmaintained app dies in about 18 months.' },
  { id: 'connect', add: 2500, mo: 0, name: 'Connect to something you already run',
    note: 'A CRM, an accounting system, a bank feed. Per system connected.' },
  { id: 'portal', add: 2500, mo: 0, name: 'Logins for your own customers',
    note: 'They see their own data and nothing else. Their questions stop arriving by email.' },
  { id: 'tenant', add: 3500, mo: 300, name: 'More than one location, brand or tenant',
    note: 'Separate data, one platform, and reporting that crosses all of them.' },
  { id: 'migrate', add: 1500, mo: 0, name: 'Bring your existing data across',
    note: 'The spreadsheets, the old system, the history. Reconciled, not just imported.' },
  { id: 'lang', add: 1500, mo: 0, name: 'A second language',
    note: 'Including right-to-left, which is a layout problem rather than a translation one.' },
  { id: 'sso', add: 2500, mo: 500, name: 'SSO, audit trail, compliance',
    note: 'Single sign-on, an immutable log of who did what, and the paperwork that goes with it.' },
];

/* --- the case-study comparison ------------------------------------------------
   A mid-market US agency, which is the band this work actually sits in.
   Researched Aug 2026 against the FullStack Labs price guide: US agency tiers
   run small-class $90–160/hr, mid-market $120–250, big-business $250–350.

   HOURS_PER_DAY is a RANGE on purpose. A day that carried a commit is not a
   timesheet, and nobody knows whether an agency bills six hours or eight for
   the same work. Publishing a range says that out loud; publishing a single
   figure would be pretending to a precision we do not have, on the one part of
   the page that is a claim about somebody else's money. */
const COMPARE = { label: 'a mid-market agency', hourly: 200, hoursPerDay: [6, 8] };

/** What the estimate builder would say for a given tier + add-ons. */
function quote(tierId, addonIds) {
  const base = BASES.find((b) => b.id === tierId);
  if (!base) return null;
  const picked = (addonIds || []).map((id) => ADDONS.find((a) => a.id === id)).filter(Boolean);
  const build = base.from + picked.reduce((s, a) => s + a.add, 0);
  const monthly = base.mo + picked.reduce((s, a) => s + a.mo, 0);
  return { base, picked, build, monthly, partnership: build >= PARTNER_AT };
}

module.exports = {
  OVERFLOW_HOURLY, PILOT, PARTNER_AT, PARTNER,
  BASES, ADDONS, COMPARE, quote,
};
