/* ============================================================================
   kaymen.dev — the price ladder

   SINGLE SOURCE OF TRUTH. Everything that quotes a price reads this file:

     · the picker on the homepage           (script.js, via window.KD_PRICING)
     · the cost block on every case study   (server/render.js)

   It used to live inside script.js, which meant the case studies could not see
   it and would have had to repeat the numbers. Repeated numbers drift, and a
   pricing page that disagrees with a case study is worse than either alone.

   This file is loaded BOTH ways: require()d by the server and served straight
   to the browser as a static .js, where it sets window.KD_PRICING. Until
   2026-08-16 the header claimed that already happened; it did not, and
   script.js carried a second copy of the ladder that had to be kept in step by
   hand. See the dual export at the bottom.

   WHERE THE NUMBERS CAME FROM
   Build tiers and add-on increments are derived from measured build effort in
   content/stats.js — generated by scripts/refresh-stats.js from real git
   history — priced at the $125/hr overflow rate. The monthlies come from the
   measured maintenance load recorded in
   unified-memory/projects/kaymen-group/retainer-pricing-ladder.md: a live
   system needs 1–8 active days a month, clustering at 2–5, and a maintenance
   day is 2–3 focused hours rather than eight.

   ONLY "FROM" PRICES ARE PUBLISHED. A published ceiling makes a client with a
   smaller budget assume you are coming for the ceiling. The total is a
   consequence of what they tick and nothing else.
   ============================================================================ */

const OVERFLOW_HOURLY = 125;

/* The pilot. A cheaper BUILD would devalue the work and attract clients who
   churn off the retainer, which is where the business actually is. A cheap paid
   pilot lowers the first step without either problem, and buys the scope
   clarity you need before quoting. */
const PILOT = { price: 750, weeks: 1 };

/* Above this a fixed build price stops being one we can deliver at, so the
   builder stops quoting and offers the partnership instead. */
const PARTNER_AT = 15000;
const PARTNER = { monthly: 3500, months: 12 };

/* Each tier carries three shapes of the same idea, because the homepage says it
   three times in three widths:
     name  — the full line, used in the picker list
     chip  — three or four words, used in the pill row
     say   — how it reads inside "I need ___", so it must start mid-sentence
   ticks are the three differentiators the old #need section hid behind a click. */
const BASES = [
  {
    id: 'running', from: 0, mo: 450,
    chip: 'Something that exists',
    name: 'Keep alive something that already works',
    say: 'someone to keep a system alive that already works',
    note: 'It exists and it runs. The person who built it is leaving, or already has.',
    ticks: ['Backups verified, not assumed', 'Patches and dependency updates', 'Someone who answers when it breaks'],
    plan: 'Patched, backed up, monitored, and small changes as they come up.',
  },
  {
    /* THE ENTRY RUNG, AND THE DEFAULT. It has been reworded twice and both
       failures were the same one: describing the WORK rather than the THING.
       "One job you still do by hand" and then "the job that comes back every
       week" both framed $2,500 as the price of a chore, and a chore is never
       worth $2,500 to anyone. What is actually being sold is a system — a real
       database with logins, that they own — for one part of the business. Price
       a system at $2,500 and it reads as cheap, which is the truth. So this rung
       names the thing, not the task, and the ticks answer "why not a
       spreadsheet" rather than describing how we work. */
    id: 'tool', from: 2500, mo: 200,
    chip: 'Your first real system',
    name: 'One part of the business, on software you own',
    say: 'a real system for the part of the business still running on spreadsheets',
    note: 'Quotes, jobs, bookings, stock, who owes what. A real database with logins for your people, not a spreadsheet that breaks when two of them open it at once.',
    ticks: ['A real database behind it, not a spreadsheet', 'Logins for everyone who needs one, no per-seat fee', 'Yours, on your infrastructure and in your accounts'],
    plan: 'Patched, backed up, monitored, and we answer.',
  },
  {
    id: 'stack', from: 6500, mo: 450,
    chip: 'Tools that do not talk',
    name: 'Work spread across tools that do not talk to each other',
    say: 'one place where the answer lives, not six tools that do not talk',
    note: 'You have the software. What you do not have is one place where the answer lives, so somebody reconciles it by hand.',
    ticks: ['One source of truth, not six exports', 'No per-seat licence, add who you like', 'Yours to take elsewhere at any time'],
    plan: 'Kept running, plus the small changes as they come up.',
  },
  {
    id: 'platform', from: 15000, mo: 1200,
    chip: 'Several systems at once',
    name: 'Several systems, several teams, and the reporting across all of it',
    say: 'several systems, several teams, and reporting that crosses all of them',
    note: 'Questions that can only be answered today by exporting everything and merging it by hand.',
    ticks: ['Ten hours of development a month', 'Reporting across every team', 'Rolls over one month if unused'],
    plan: '10 hours of development a month, rolling over one month.',
  },
];

/* The escape hatch, and the only place the pilot is offered. It used to be
   buried in fine print under the builder, which is the worst possible spot for
   the thing that converts somebody who cannot pick a row. It is deliberately
   NOT a fifth price tier: quote() does not know about it. */
const UNSURE = {
  id: 'unsure',
  chip: 'Not sure yet',
  name: 'A straight answer about whether this is software at all',
  say: 'a straight answer about whether this is software at all',
  note: 'Sometimes it is a process problem wearing a software costume, and the honest answer is to build nothing. We will say so.',
  ticks: ['No payment, no commitment', 'We name the cheaper option if there is one', 'You leave with a shape and a number, or a reason not to'],
};

const ADDONS = [
  { id: 'mobile', add: 5000, mo: 300, name: 'An app in the App Store and Google Play',
    note: 'Native, in both stores, updated over the air. Apple and Google force SDK bumps, so an unmaintained app dies in about 18 months.' },
  { id: 'connect', add: 2500, mo: 0, name: 'Connect to something you already run',
    note: 'A CRM, an accounting system, a bank feed. Per system connected.' },
  { id: 'portal', add: 2500, mo: 0, name: 'Logins for your own customers',
    note: 'They see their own data and nothing else. Their questions stop arriving by email.' },
  { id: 'tenant', add: 3500, mo: 300, name: 'More than one location, brand or tenant',
    note: 'Separate data, one platform, and reporting that crosses all of them.' },
  { id: 'migrate', add: 1500, mo: 0, name: 'Bring your existing data across',
    note: 'The spreadsheets, the old system, the history. Reconciled, not just imported.' },
  { id: 'lang', add: 1500, mo: 0, name: 'A second language',
    note: 'Including right-to-left, which is a layout problem rather than a translation one.' },
  { id: 'sso', add: 2500, mo: 500, name: 'SSO, audit trail, compliance',
    note: 'Single sign-on, an immutable log of who did what, and the paperwork that goes with it.' },
];

/* --- the case-study comparison ------------------------------------------------
   A mid-market US agency, which is the band this work actually sits in.
   Researched Aug 2026 against the FullStack Labs price guide: US agency tiers
   run small-class $90–160/hr, mid-market $120–250, big-business $250–350.

   HOURS_PER_DAY is a RANGE on purpose. A day that carried a commit is not a
   timesheet, and nobody knows whether an agency bills six hours or eight for
   the same work. Publishing a range says that out loud; publishing a single
   figure would be pretending to a precision we do not have, on the one part of
   the page that is a claim about somebody else's money. */
const COMPARE = { label: 'a mid-market agency', hourly: 200, hoursPerDay: [6, 8] };

/** What the estimate builder would say for a given tier + add-ons. */
function quote(tierId, addonIds) {
  const base = BASES.find((b) => b.id === tierId);
  if (!base) return null;
  const picked = (addonIds || []).map((id) => ADDONS.find((a) => a.id === id)).filter(Boolean);
  const build = base.from + picked.reduce((s, a) => s + a.add, 0);
  const monthly = base.mo + picked.reduce((s, a) => s + a.mo, 0);
  return { base, picked, build, monthly, partnership: build >= PARTNER_AT };
}

/* --- what the alternative costs, for the hero -------------------------------
   RESEARCHED Aug 2026 against published list prices, for a team of five on
   mid-tier plans. This is the only claim on the homepage about somebody else's
   pricing, so it gets the same treatment the $200/hr agency rate got.

   No stack is ever exactly this — everyone's mix of tools and tiers differs,
   which is why the panel says "team of five" rather than implying a quote.
   These are chosen as the middle of a real range, not the top of it:

     Work & projects      Monday Standard $12/seat x5. Asana $10.99, ClickUp $7.
     CRM & pipeline       HubSpot Starter $15/seat annual x5. Pipedrive Lite $14.
     Invoicing & books    QuickBooks Essentials $85 and Xero Growing $55, midpoint.
     Forms & scheduling   Jotform Bronze $34 plus Calendly Standard $10 on ~2 seats.
     Files & e-signature  Storage plus DocuSign from $10.

   Google Workspace is deliberately NOT counted. At $14/seat it would add $70 and
   make the total look better, but email and documents are not a business system
   doing half a job — including them would be padding, and the argument does not
   need it.

   afterHires: the per-seat lines run about $39 a head, so three more people add
   roughly $117. Everything is a "from" and the total is summed in rentTotal(),
   never typed, so the panel cannot disagree with its own line items. */
const RENT_STACK = {
  label: 'team of five',
  rows: [
    { name: 'Work & projects', mo: 60 },
    { name: 'CRM & pipeline', mo: 75 },
    { name: 'Invoicing & books', mo: 70 },
    { name: 'Forms & scheduling', mo: 45 },
    { name: 'Files & e-signature', mo: 40 },
  ],
  hires: 3,
  afterHires: 405,
};
const rentTotal = () => RENT_STACK.rows.reduce((s, r) => s + r.mo, 0);

const money = (n) => '$' + Math.round(n).toLocaleString('en-US');

/** The picker list, display-ready.
 *
 *  Every string the homepage shows is derived here rather than written twice.
 *  The two figures either side of the slash are the build/monthly split, which
 *  is the distinction the section exists to make: one is once, one is forever.
 */
function routes() {
  return BASES.map((b) => ({
    id: b.id, chip: b.chip, name: b.name, say: b.say, note: b.note, ticks: b.ticks,
    price: b.from ? 'from ' + money(b.from) : 'no build',
    n1: b.from ? money(b.from) : 'No build fee',
    s1: b.from ? 'to build, once' : 'we take it as it is',
    n2: money(b.mo),
    s2: b.from ? 'a month after that' : 'a month',
  })).concat([{
    id: UNSURE.id, chip: UNSURE.chip, name: UNSURE.name, say: UNSURE.say,
    note: UNSURE.note, ticks: UNSURE.ticks,
    price: 'free',
    n1: 'Free', s1: 'one conversation',
    n2: money(PILOT.price),
    s2: `only if you want a working prototype too, credited in full`,
  }]);
}

const API = {
  OVERFLOW_HOURLY, PILOT, PARTNER_AT, PARTNER,
  BASES, ADDONS, UNSURE, COMPARE, quote, routes,
  RENT_STACK, rentTotal,
};

/* Dual export. require()d by server/render.js, and served as a plain script to
   the browser, where script.js reads window.KD_PRICING. Neither side gets its
   own copy of the numbers. */
if (typeof module !== 'undefined' && module.exports) module.exports = API;
if (typeof window !== 'undefined') window.KD_PRICING = API;
