/* ============================================================================
   kaymen.dev — the price ladder

   SINGLE SOURCE OF TRUTH. Everything that quotes a price reads this file:

     · the picker on the homepage           (script.js, via window.KD_PRICING)
     · the cost block on every case study   (server/render.js)

   It used to live inside script.js, which meant the case studies could not see
   it and would have had to repeat the numbers. Repeated numbers drift, and a
   pricing page that disagrees with a case study is worse than either alone.

   This file is loaded BOTH ways: require()d by the server and served straight
   to the browser as a static .js, where it sets window.KD_PRICING. Until
   2026-08-16 the header claimed that already happened; it did not, and
   script.js carried a second copy of the ladder that had to be kept in step by
   hand. See the dual export at the bottom.

   WHERE THE NUMBERS CAME FROM
   Build tiers and add-on increments are derived from measured build effort in
   content/stats.js — generated by scripts/refresh-stats.js from real git
   history — priced at the $125/hr overflow rate. The monthlies come from the
   measured maintenance load recorded in
   unified-memory/projects/kaymen-group/retainer-pricing-ladder.md: a live
   system needs 1–8 active days a month, clustering at 2–5, and a maintenance
   day is 2–3 focused hours rather than eight.

   ONLY "FROM" PRICES ARE PUBLISHED. A published ceiling makes a client with a
   smaller budget assume you are coming for the ceiling. The total is a
   consequence of what they tick and nothing else.
   ============================================================================ */

/* NO LONGER PUBLISHED. This is now an internal derivation basis only — the
   build tiers below are measured effort priced at this rate, and the case-study
   comparison is this rate against COMPARE.hourly. The site stopped printing it
   on 2026-08-18: it was the only per-unit price about us on a page arguing
   against per-unit pricing, it reframed the retainer as consumption rather than
   availability, and it capped the monthly at hours x rate. See the comment
   beside the fine print in index.html. Do not put it back on a page. */
const OVERFLOW_HOURLY = 125;

/* The pilot. A cheaper BUILD would devalue the work and attract clients who
   churn off the retainer, which is where the business actually is. A cheap paid
   pilot lowers the first step without either problem, and buys the scope
   clarity you need before quoting. */
const PILOT = { price: 750, weeks: 1 };

/* Above this a fixed build price stops being one we can deliver at, so the
   builder stops quoting and offers the partnership instead. */
const PARTNER_AT = 15000;
const PARTNER = { monthly: 3500, months: 12 };

/* Each tier carries three shapes of the same idea, because the homepage says it
   three times in three widths:
     product — WHAT YOU GET, and the one to use anywhere a label sits next to
               money. Added 2026-08-19 after Ariel could not tell the rungs
               apart, and the cause was this: `chip` describes the PROBLEM. That
               reads correctly in a pill row answering "which of these are you"
               and INVERTS the moment it sits above a price — the live card
               headed "Tools that do not talk · from $6,500" reads as paying
               $6,500 FOR tools that do not talk, and "Something that exists ·
               $450/mo" is worse. Same class of mistake as the ticks: copy
               written for one context reused in another.
     name  — the full line, used in the picker list
     chip  — three or four words, used in the pill row
     say   — how it reads inside "I need ___", so it must start mid-sentence

   `axes` replaced `ticks` on 2026-08-19, same cause as `product`. The old ticks
   were three FREELY CHOSEN attributes per rung — twelve different lines across
   four cards — so there was nothing to read across and no way to tell the rungs
   apart. Worse, most of them were true of every rung, so listing backups on the
   first card alone implied the other three had none, and "no per-seat fee"
   appeared on two cards as though it distinguished them. Everything universal
   now lives in UNIVERSAL, said once above the row; each card answers the same
   four questions in AXES, in the same order.

   THE RULE THAT KEEPS IT HONEST, and the one scripts/verify-ask.js enforces: an
   axis whose answer is identical on ALL FOUR rungs is a universal wearing a
   label, and belongs in UNIVERSAL. Two rungs coinciding is fine and is often the
   point — `running` and `stack` both include small changes and `tool` does not,
   which is a real difference and half the reason $450 sits above $300. */

/* True of every rung, so said once rather than scattered through the cards as
   though it were a difference. The last line is not marketing: clause 5 of
   legal/CLIENT-AGREEMENT.md is what makes it enforceable. */
const UNIVERSAL = [
  'You own the code, the data and the servers',
  'Logins for everyone, no per-seat fee',
  'Backups verified, patched, monitored',
  'A person answers when it breaks',
  'Take it elsewhere any time, no exit fee',
];

/* The four questions every card answers, in this order. Named here so a rung
   cannot quietly grow a fifth or answer them in a different order. */
const AXES = ['Covers', 'Replaces', 'Reporting', 'Changes'];

const BASES = [
  {
    id: 'running', from: 0, mo: 450,
    product: 'Keep it running',
    chip: 'Something that exists',
    name: 'Keep alive something that already works',
    say: 'someone to keep a system alive that already works',
    note: 'It exists and it runs. The person who built it is leaving, or already has.',
    axes: [
      'A system you already have',
      'Nothing — we take it as it is',
      'Whatever it already does',
      'Small changes, as they come',
    ],
  },
  {
    /* THE ENTRY RUNG, AND THE DEFAULT. It has been reworded twice and both
       failures were the same one: describing the WORK rather than the THING.
       "One job you still do by hand" and then "the job that comes back every
       week" both framed $2,500 as the price of a chore, and a chore is never
       worth $2,500 to anyone. What is actually being sold is a system — a real
       database with logins, that they own — for one part of the business. Price
       a system at $2,500 and it reads as cheap, which is the truth. So this rung
       names the thing, not the task.

       THE MONTHLY WENT $200 to $300 on 2026-08-16 (Ariel: "$200 a month is
       low"). He is right, and the ladder's own evidence says so: a light live
       system runs ~5 h/mo, so $200 was an effective $40/hr against a published
       $125/hr overflow rate and a $200/hr agency comparison. The retainer is
       where the business is; pricing it at a third of the overflow rate meant
       maintenance was being subsidised out of build revenue.

       WHY THIS WAS NOT SAFE TO DO ALONE. $200 sat under the $290 rent-stack
       total, and the hero panel put them side by side — so raising it inverts
       the one juxtaposition the panel had. It is only defensible because the
       labour line landed in the same change: the comparison is no longer $290
       against $200, it is $290 PLUS the person reconciling against $300 flat.
       Fixing the argument is what paid for the price rise. Do not undo one
       without the other.

       Still deliberately the cheapest thing on the page, and still a clear step
       below `stack` at $450. */
    id: 'tool', from: 2500, mo: 300,
    product: 'One part of the business',
    chip: 'Your first real system',
    name: 'One part of the business, on software you own',
    say: 'a real system for the part of the business still running on spreadsheets',
    note: 'Quotes, jobs, bookings, stock, who owes what. A real database with logins for your people, not a spreadsheet that breaks when two of them open it at once.',
    /* CHANGES SAYS "QUOTED", NOT "INCLUDED", AND THAT IS NOT AN OVERSIGHT. This
       is the only rung whose monthly never promised change work — the other
       three do. Writing "small changes as they come up" here to make the four
       cards look even would be inventing a commercial term, and it would also
       erase the only reason $300 sits below $450 for a comparable system. */
    axes: [
      'One workflow, end to end',
      'A tool or a spreadsheet',
      'That one part only',
      'Quoted as they come',
    ],
  },
  {
    id: 'stack', from: 6500, mo: 450,
    product: 'The whole toolset',
    chip: 'Tools that do not talk',
    name: 'Work spread across tools that do not talk to each other',
    say: 'one place where the answer lives, not six tools that do not talk',
    note: 'You have the software. What you do not have is one place where the answer lives, so somebody reconciles it by hand.',
    axes: [
      'Several tools that do not talk',
      'Three to six tools',
      'The whole business',
      'Small changes, as they come',
    ],
  },
  {
    id: 'platform', from: 15000, mo: 1200,
    product: 'Several teams, one platform',
    chip: 'Several systems at once',
    name: 'Several systems, several teams, and the reporting across all of it',
    say: 'several systems, several teams, and reporting that crosses all of them',
    note: 'Questions that can only be answered today by exporting everything and merging it by hand.',
    axes: [
      'Multiple teams and locations',
      'A whole stack',
      'Every team, every location',
      '10 dev hours a month, rolls over',
    ],
  },
];

/* The escape hatch, and the only place the pilot is offered. It used to be
   buried in fine print under the builder, which is the worst possible spot for
   the thing that converts somebody who cannot pick a row. It is deliberately
   NOT a fifth price tier: quote() does not know about it. */
const UNSURE = {
  id: 'unsure',
  chip: 'Not sure yet',
  name: 'A straight answer about whether this is software at all',
  say: 'a straight answer about whether this is software at all',
  note: 'Sometimes it is a process problem wearing a software costume, and the honest answer is to build nothing. We will say so.',
  ticks: ['No payment, no commitment', 'We name the cheaper option if there is one', 'You leave with a shape and a number, or a reason not to'],
};

const ADDONS = [
  { id: 'mobile', add: 5000, mo: 300, name: 'An app in the App Store and Google Play',
    note: 'Native, in both stores, updated over the air. Apple and Google force SDK bumps, so an unmaintained app dies in about 18 months.' },
  { id: 'connect', add: 2500, mo: 0, name: 'Connect to something you already run',
    note: 'A CRM, an accounting system, a bank feed. Per system connected.' },
  { id: 'portal', add: 2500, mo: 0, name: 'Logins for your own customers',
    note: 'They see their own data and nothing else. Their questions stop arriving by email.' },
  { id: 'tenant', add: 3500, mo: 300, name: 'More than one location, brand or tenant',
    note: 'Separate data, one platform, and reporting that crosses all of them.' },
  { id: 'migrate', add: 1500, mo: 0, name: 'Bring your existing data across',
    note: 'The spreadsheets, the old system, the history. Reconciled, not just imported.' },
  { id: 'lang', add: 1500, mo: 0, name: 'A second language',
    note: 'Including right-to-left, which is a layout problem rather than a translation one.' },
  { id: 'sso', add: 2500, mo: 500, name: 'SSO, audit trail, compliance',
    note: 'Single sign-on, an immutable log of who did what, and the paperwork that goes with it.' },
];

/* --- the case-study comparison ------------------------------------------------
   A mid-market US agency, which is the band this work actually sits in.
   Researched Aug 2026 against the FullStack Labs price guide: US agency tiers
   run small-class $90–160/hr, mid-market $120–250, big-business $250–350.

   HOURS_PER_DAY is a RANGE on purpose. A day that carried a commit is not a
   timesheet, and nobody knows whether an agency bills six hours or eight for
   the same work. Publishing a range says that out loud; publishing a single
   figure would be pretending to a precision we do not have, on the one part of
   the page that is a claim about somebody else's money. */
const COMPARE = { label: 'a mid-market agency', hourly: 200, hoursPerDay: [6, 8] };

/** What the estimate builder would say for a given tier + add-ons. */
function quote(tierId, addonIds) {
  const base = BASES.find((b) => b.id === tierId);
  if (!base) return null;
  const picked = (addonIds || []).map((id) => ADDONS.find((a) => a.id === id)).filter(Boolean);
  const build = base.from + picked.reduce((s, a) => s + a.add, 0);
  const monthly = base.mo + picked.reduce((s, a) => s + a.mo, 0);
  return { base, picked, build, monthly, partnership: build >= PARTNER_AT };
}

/* --- what the alternative costs, for the hero -------------------------------
   RESEARCHED Aug 2026 against published list prices, for a team of five on
   mid-tier plans. This is the only claim on the homepage about somebody else's
   pricing, so it gets the same treatment the $200/hr agency rate got.

   No stack is ever exactly this — everyone's mix of tools and tiers differs,
   which is why the panel says "team of five" rather than implying a quote.
   These are chosen as the middle of a real range, not the top of it:

     Work & projects      Monday Standard $12/seat x5. Asana $10.99, ClickUp $7.
     CRM & pipeline       HubSpot Starter $15/seat annual x5. Pipedrive Lite $14.
     Invoicing & books    QuickBooks Essentials $85 and Xero Growing $55, midpoint.
     Forms & scheduling   Jotform Bronze $34 plus Calendly Standard $10 on ~2 seats.
     Files & e-signature  Storage plus DocuSign from $10.

   Google Workspace is deliberately NOT counted. At $14/seat it would add $70 and
   make the total look better, but email and documents are not a business system
   doing half a job — including them would be padding, and the argument does not
   need it.

   afterHires: the per-seat lines run about $39 a head, so three more people add
   roughly $117. Everything is a "from" and the total is summed in rentTotal(),
   never typed, so the panel cannot disagree with its own line items.

   THE LABOUR LINE (added 2026-08-16, Ariel's note). The panel used to stop at
   the licences, and that was its weakest point: $290 is not a frightening
   number, and this file already concedes the page does not claim to be cheaper
   in year one. The cost that actually hurts a business running five disconnected
   tools is the PERSON reconciling between them, and it is nowhere on the invoice
   — Ariel's exact words were "we dont necessarily save u money on the saas fee
   but we save u money on manpower".

   reconcileHours is deliberately FOUR — half a day a week, the low end of
   plausible, because the argument gets weaker if it sounds greedy. The number
   published is not a salary, it is a BREAK-EVEN: reconcileBreakEven() divides
   the licence total by those hours, so the claim is arithmetic the reader can
   check rather than an assertion about their payroll. At $290 over 17.3 h/mo it
   lands near $17/hr, i.e. below almost any wage — which is the point. It is
   computed, never typed, for the same reason as rentTotal().

   Note the scope: the ladder doc warns "do not build a per-seat TCO argument; it
   does not hold at this size", and it is right. This is not a per-seat argument
   and it is not aimed at the three-person brokerage — it sits on a panel that
   says "team of five" out loud, which is the size where somebody really is
   spending half a day a week on this. */
const RENT_STACK = {
  label: 'team of five',
  rows: [
    { name: 'Work & projects', mo: 60 },
    { name: 'CRM & pipeline', mo: 75 },
    { name: 'Invoicing & books', mo: 70 },
    { name: 'Forms & scheduling', mo: 45 },
    { name: 'Files & e-signature', mo: 40 },
  ],
  hires: 3,
  afterHires: 405,
  reconcileHours: 4,
};
const rentTotal = () => RENT_STACK.rows.reduce((s, r) => s + r.mo, 0);

/** Hours a month behind RENT_STACK.reconcileHours — 52 weeks over 12 months. */
const reconcileMonthly = () => (RENT_STACK.reconcileHours * 52) / 12;

/** The wage at which the person costs the same as every licence combined. */
const reconcileBreakEven = () => rentTotal() / reconcileMonthly();

const money = (n) => '$' + Math.round(n).toLocaleString('en-US');

/** The picker list, display-ready.
 *
 *  Every string the homepage shows is derived here rather than written twice.
 *  The two figures either side of the slash are the build/monthly split, which
 *  is the distinction the section exists to make: one is once, one is forever.
 */
function routes() {
  return BASES.map((b) => ({
    id: b.id, chip: b.chip, product: b.product, name: b.name, say: b.say, note: b.note,
    /* Paired with their labels HERE rather than in script.js, so the questions
       and the answers cannot drift apart and a rung that grows a fifth answer is
       loud about it instead of rendering an unlabelled row. Only the rungs have
       `axes` — the pilot is not a package, which is why the comparison grid keys
       off their presence rather than filtering on id. */
    axes: b.axes.map((v, i) => {
      if (!AXES[i]) throw new Error(`pricing: rung "${b.id}" has more answers than AXES has questions`);
      return [AXES[i], v];
    }),
    price: b.from ? 'from ' + money(b.from) : 'no build',
    n1: b.from ? money(b.from) : 'No build fee',
    s1: b.from ? 'to build, once' : 'we take it as it is',
    n2: money(b.mo),
    s2: b.from ? 'a month after that' : 'a month',
    /* One compact line for the comparison grid, where the money is deliberately
       subordinate to what you get. Assembled here so no second file has to know
       how a "no build fee" rung reads. */
    money: b.from ? `from ${money(b.from)} · ${money(b.mo)}/mo` : `no build fee · ${money(b.mo)}/mo`,
  })).concat([{
    id: UNSURE.id, chip: UNSURE.chip, name: UNSURE.name, say: UNSURE.say,
    note: UNSURE.note, ticks: UNSURE.ticks,
    price: 'free',
    n1: 'Free', s1: 'one conversation',
    n2: money(PILOT.price),
    s2: `only if you want a working prototype too, credited in full`,
    money: `free · ${money(PILOT.price)} pilot, optional`,
  }]);
}

/* --- what it costs to scale --------------------------------------------------
   The homepage comparison chart, added 2026-08-18. It answers the one question
   the picker below it cannot: "against what?".

   EVERY LIST PRICE HERE WAS CHECKED ON 2026-08-18, and each carries its source
   beside it. This is the second place on the site making a claim about somebody
   else's pricing (RENT_STACK is the first), so it gets the same treatment:
   mid-of-range, monthly billing where the vendor publishes one, annual where
   that is the only option and said so on screen.

   These rot. QuickBooks raised Plus 41% on 1 August 2026 while this was being
   built, which is the argument for keeping the check date on the page rather
   than in a comment nobody reads.

   THREE THINGS THAT ARE NOT OBVIOUS, all three got wrong on the first pass:

   1. monday sells SEATS IN BLOCKS - 3 minimum, then multiples of 5. A team of
      six pays for ten. Modelled in blockSeats(). Drawing it as a smooth
      per-head slope understates it at exactly the sizes most visitors are.
   2. HubSpot Professional carries a MANDATORY one-time $1,500 onboarding fee.
      They have a build fee too. Ours is the only one anybody prints.
   3. OUR OWN ROW IS NOT FLAT EITHER. At forty people the server really does
      have to get bigger, and pretending otherwise would make this chart exactly
      as dishonest as the ones it argues with. INFRA is that cost, it steps four
      times, and it is stated separately because it is paid to the client's own
      provider with no markup from us.

   The chart is priced at the TOOL rung, not stack. A CRM is "one part of the
   business, on software you own"; comparing our whole-toolset price against
   their single product compares the wrong things, and that was the only reason
   we looked expensive at small headcounts. */

const SCALE_MONTHS = 36;
const SCALE_DEFAULT_SEATS = 10;
const SCALE_SEAT_RANGE = [3, 40];
const SCALE_CHECKED = 'August 2026';
/** The rung the comparison row is priced at: like-for-like with a single CRM. */
const SCALE_RUNG = 'tool';

/** monday: 3-seat minimum, then multiples of 5. A team of six pays for ten. */
const blockSeats = (n) => (n <= 3 ? 3 : Math.ceil(n / 5) * 5);

const CRMS = [
  /* salesforce.com/sales/pricing - Enterprise, annual billing only */
  { name: 'Salesforce Sales Cloud', tier: 'Enterprise', seat: 175, once: 0, blocks: false,
    note: '$175 per user, annual billing only' },
  /* Dynamics 365 Sales Enterprise, annual commitment, quoted through a partner */
  { name: 'Microsoft Dynamics 365 Sales', tier: 'Enterprise', seat: 105, once: 0, blocks: false,
    note: '$105 per user, annual commitment' },
  /* HubSpot Sales Hub Professional - $90 annual, $100 monthly, +$1,500 onboarding */
  { name: 'HubSpot Sales Hub', tier: 'Professional', seat: 100, once: 1500, blocks: false,
    note: '$100 per user monthly, plus $1,500 onboarding' },
  { name: 'Salesforce Sales Cloud', tier: 'Pro Suite', seat: 100, once: 0, blocks: false,
    note: '$100 per user' },
  /* Zoho CRM Enterprise - $40 annual, $50 monthly */
  { name: 'Zoho CRM', tier: 'Enterprise', seat: 50, once: 0, blocks: false,
    note: '$50 per user monthly' },
  /* Pipedrive renamed every plan in 2025: Professional and Power both folded
     into Premium. Anything quoting "Pipedrive Professional" is pricing a tier
     that no longer exists. */
  { name: 'Pipedrive', tier: 'Premium', seat: 49, once: 0, blocks: false,
    note: '$49 per user, annual billing' },
  /* monday CRM Pro - $28 annual, $41 monthly, 3-seat min then blocks of 5 */
  { name: 'monday CRM', tier: 'Pro', seat: 41, once: 0, blocks: true,
    note: '$41 per seat monthly, 3-seat minimum then blocks of 5' },
];

/* The glue. NOT an alternative to the rows above - it sits ON TOP of whichever
   one you pick, because none of them talks to your books, forms or storage on
   its own. Zapier Professional, monthly billing, PUBLISHED tiers only; the
   in-between tiers are interpolations, and interpolations are guesses. */
const GLUE_TIERS = [
  { upTo: 5,   tasks: '2,000',  mo: 73.50 },
  { upTo: 25,  tasks: '10,000', mo: 193.50 },
  { upTo: 50,  tasks: '20,000', mo: 283.50 },
  { upTo: 999, tasks: '50,000', mo: 433.50 },
];
const glueTier = (n) => GLUE_TIERS.filter((t) => n <= t.upTo)[0];

/* Our infrastructure. Hetzner-class compute is genuinely small - 4 vCPU/8GB is
   about EUR 8.50 a month - so these figures are the whole bill around it:
   backups, object storage for documents, transactional email, TLS, domain.
   PAID TO THE CLIENT'S OWN PROVIDER, not to us, which is why it is a separate
   line rather than folded into the monthly. */
const INFRA = [
  { upTo: 10,  mo: 35,  spec: '2-4 vCPU, backups, storage, mail' },
  { upTo: 25,  mo: 55,  spec: '4 vCPU / 8GB, backups, storage, mail' },
  { upTo: 50,  mo: 90,  spec: '8 vCPU / 16GB, backups, storage, mail' },
  { upTo: 999, mo: 150, spec: 'dedicated, backups, storage, mail' },
];
const infraAt = (n) => INFRA.filter((t) => n <= t.upTo)[0];

const crmMonthly = (row, n) => row.seat * (row.blocks ? blockSeats(n) : n);
const oursMonthly = (n) => BASES.find((b) => b.id === SCALE_RUNG).mo + infraAt(n).mo;

/** Every row of the chart at a given headcount. ONE function, two renderers:
 *  server/render.js turns it into HTML, script.js mutates that same DOM from
 *  it. Neither of them owns the arithmetic. */
function scaleRows(seats) {
  const n = Math.max(SCALE_SEAT_RANGE[0], Math.min(SCALE_SEAT_RANGE[1], Math.round(seats) || SCALE_DEFAULT_SEATS));
  const base = BASES.find((b) => b.id === SCALE_RUNG);
  const glue = glueTier(n);
  const glueYear = glue.mo * 12;
  const oursYear = oursMonthly(n) * 12;
  const inf = infraAt(n);

  const rows = CRMS.map((c) => {
    const year = crmMonthly(c, n) * 12;
    return {
      kind: 'them', name: c.name, tier: c.tier, note: c.note,
      per: money(c.seat) + '/user',
      years: [year + c.once, year, year],
    };
  }).sort((a, b) => (b.years[0] + b.years[1] + b.years[2]) - (a.years[0] + a.years[1] + a.years[2]));

  rows.push({
    kind: 'glue', name: 'Zapier, to glue them together', tier: glue.tasks + ' tasks a month',
    note: 'overage bills at 1.25x, and Zaps halt at 3x', per: '',
    years: [glueYear, glueYear, glueYear],
    tag: 'on top of whichever you pick',
  });
  rows.push({
    kind: 'ours', name: 'Your own system',
    tier: money(base.from) + ' once, then ' + money(base.mo) + '/mo',
    note: 'no per-seat licence, ever', per: '$0/user',
    years: [base.from + oursYear, oursYear, oursYear],
    tag: money(inf.mo) + '/mo of that is infrastructure, paid to your provider - no markup',
  });

  rows.forEach((r) => { r.total = r.years[0] + r.years[1] + r.years[2]; });
  const top = Math.max.apply(null, rows.map((r) => r.total));
  rows.forEach((r) => { r.widths = r.years.map((v) => (v / top) * 100); });
  return { seats: n, rows, ours: rows[rows.length - 1].total, oursYear };
}

/** The note beside the chart. It concedes when the numbers say to concede,
 *  which is the only reason anybody believes it when it does not. */
function scaleAside(seats) {
  const r = scaleRows(seats);
  const n = r.seats;
  const under = CRMS.filter((c) => c.once + crmMonthly(c, n) * 12 * 3 < r.ours);
  if (under.length) {
    let cross = null;
    for (let k = n + 1; k <= 200 && !cross; k++) {
      const at = scaleRows(k);
      const cheapest = Math.min.apply(null, CRMS.map((c) => c.once + crmMonthly(c, k) * 12 * 3));
      if (cheapest > at.ours) cross = k;
    }
    const names = under.map((c) => c.name);
    return {
      title: 'Why the cheap rows win here',
      html: '<b>' + names.join(', ') + '</b> ' + (names.length === 1 ? 'comes' : 'come') +
        ' in under us at ' + n + ' people, and we are not going to pretend otherwise. They are licences, ' +
        'not systems: they stop the day you stop paying, and you cannot take them anywhere. Under about <b>' +
        (cross ? cross + ' people' : 'any size we build for') +
        '</b> that trade is usually the right one, and we will say so on a call.',
    };
  }
  const dearest = CRMS[0];
  return {
    title: 'Why year one looks expensive',
    html: 'Ours is the only row with a build fee, so <b>year one is the only year we cost more</b>. After it, <b>' +
      money(r.oursYear) + ' a year</b> against ' + money(crmMonthly(dearest, n) * 12) +
      ' &mdash; every year, at any headcount, and at the end of it the system is yours rather than rented back to you.',
  };
}

const API = {
  OVERFLOW_HOURLY, PILOT, PARTNER_AT, PARTNER,
  BASES, ADDONS, UNSURE, COMPARE, quote, routes, UNIVERSAL, AXES,
  RENT_STACK, rentTotal, reconcileMonthly, reconcileBreakEven,
  CRMS, GLUE_TIERS, INFRA, SCALE_MONTHS, SCALE_DEFAULT_SEATS, SCALE_SEAT_RANGE,
  SCALE_CHECKED, SCALE_RUNG, blockSeats, glueTier, infraAt, crmMonthly, oursMonthly,
  scaleRows, scaleAside, money,
};

/* Dual export. require()d by server/render.js, and served as a plain script to
   the browser, where script.js reads window.KD_PRICING. Neither side gets its
   own copy of the numbers. */
if (typeof module !== 'undefined' && module.exports) module.exports = API;
if (typeof window !== 'undefined') window.KD_PRICING = API;
