/* ============================================================================
   kaymen.dev — write the icon set from content/logo.js

     node scripts/build-icons.js

   Writes favicon.svg, assets/mark.svg and the three PNG sizes. Output is
   committed and served statically, the same arrangement as assets/og, so
   production never needs an image toolchain.

   WHY THE PNGs HAVE TO EXIST. Both index.html files pointed apple-touch-icon
   at favicon.svg, and iOS Safari does not accept SVG there: it silently
   ignores the tag and puts a screenshot of the page on the home screen
   instead. Android's maskable icon support for SVG is patchy in the same way.
   An SVG favicon covers desktop browsers and nothing else.

   RASTERISING WITHOUT A DEPENDENCY. The one image tool on this machine lives
   in _tools/showcase and belongs to the showcase harness, which is shared with
   other projects. Rather than reach into it or add playwright to a site that
   otherwise has no build step, this drives whatever Chrome is already
   installed over the DevTools protocol using Node's built-in WebSocket. No
   package to install, nothing new in package.json, and it fails loudly rather
   than writing a broken icon if Chrome is missing.
   ============================================================================ */

const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn } = require('child_process');
const LOGO = require('../content/logo.js');

const ROOT = path.join(__dirname, '..');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const CHROMES = [
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
];

/* Every PNG the manifests and iOS actually ask for. 180 is Apple's current
   apple-touch-icon size; 192 and 512 are what the web app manifest spec names
   as the two that must be present. */
const PNGS = [
  { file: 'apple-touch-icon.png', px: 180 },
  { file: 'icon-192.png', px: 192 },
  { file: 'icon-512.png', px: 512 },
];

function write(rel, body) {
  const abs = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, body);
  const n = Buffer.isBuffer(body) ? body.length : Buffer.byteLength(body);
  console.log(`  ${rel.padEnd(30)} ${String(n).padStart(7)} bytes`);
}

async function cdp(port) {
  let list;
  for (let i = 0; i < 40; i++) {
    try {
      list = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
      if (list.some((t) => t.type === 'page')) break;
    } catch { /* not up yet */ }
    await sleep(250);
  }
  const page = (list || []).find((t) => t.type === 'page');
  if (!page) throw new Error('Chrome started but never exposed a page target');

  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((res, rej) => { ws.addEventListener('open', res); ws.addEventListener('error', rej); });
  let id = 0;
  const pending = new Map();
  ws.addEventListener('message', (e) => {
    const m = JSON.parse(e.data);
    if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); }
  });
  const send = (method, params = {}) => new Promise((res) => {
    const i = ++id;
    pending.set(i, res);
    ws.send(JSON.stringify({ id: i, method, params }));
  });
  return { send, close: () => ws.close() };
}

(async () => {
  console.log('kaymen.dev icons\n');

  /* 1. the vectors, straight out of the module */
  const favicon = LOGO.tile({ kind: 'deep' });
  write('favicon.svg', `<!-- generated by scripts/build-icons.js from content/logo.js; do not hand-edit -->\n${favicon}\n`);
  write('assets/mark.svg', `${LOGO.glyph({ keyFill: '#ffffff', flankFill: '#ffffff', flankOpacity: 0.62 })}\n`);

  /* 2. the rasters. one page, resized per icon, screenshotting a div that
        holds the tile at exactly the target size so there is no resampling. */
  const exe = CHROMES.find((p) => fs.existsSync(p));
  if (!exe) throw new Error(`No Chrome or Edge found. Looked in:\n  ${CHROMES.join('\n  ')}`);

  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'kd-icons-'));
  const port = 9333;
  const chrome = spawn(exe, [
    '--headless=new', '--disable-gpu', '--hide-scrollbars', '--no-first-run',
    `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, 'about:blank',
  ], { stdio: 'ignore', detached: false });

  let conn;
  try {
    conn = await cdp(port);
    await conn.send('Page.enable');

    for (const { file, px } of PNGS) {
      const html = `<!doctype html><meta charset="utf-8">` +
        `<style>html,body{margin:0;padding:0;background:transparent}` +
        `svg{display:block;width:${px}px;height:${px}px}</style>` +
        LOGO.tile({ kind: 'deep' });
      await conn.send('Emulation.setDeviceMetricsOverride',
        { width: px, height: px, deviceScaleFactor: 1, mobile: false });
      await conn.send('Page.navigate', { url: `data:text/html;charset=utf-8,${encodeURIComponent(html)}` });
      await sleep(320);
      const shot = await conn.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
      const buf = Buffer.from(shot.result.data, 'base64');
      /* A PNG always opens with the 8-byte signature. Anything else means the
         screenshot came back empty and we would be committing a broken icon. */
      if (buf.length < 200 || buf.toString('hex', 0, 8) !== '89504e470d0a1a0a') {
        throw new Error(`${file} came back as ${buf.length} bytes and is not a PNG`);
      }
      write(file, buf);
    }
  } finally {
    if (conn) conn.close();
    try { chrome.kill(); } catch { /* already gone */ }
    await sleep(300);
    try { fs.rmSync(profile, { recursive: true, force: true }); } catch { /* Chrome may still hold it */ }
  }

  console.log('\ndone.');
})().catch((e) => { console.error('\nFAILED:', e.message); process.exit(1); });
